"use client";

import { useEffect, useState } from "react";
import { type Period, type ReportType, type Source } from "../lib/report";

const OPENAI_KEY = "iitp-openai-api-key"; const GEMINI_KEY = "iitp-gemini-api-key";
type ApiResult = { ok: boolean; text?: string; sources: { title: string; url: string }[]; error?: string };
type TemplateResult = { fileName: string; fileType?: string; markdown?: string; error?: string; warnings?: { message: string }[]; };
const sourceOptions: { value: Source; label: string; icon: string }[] = [{ value: "government", label: "정부·공공기관", icon: "▤" }, { value: "research", label: "연구·학술", icon: "⌬" }, { value: "news", label: "뉴스", icon: "▥" }, { value: "company", label: "기업", icon: "◫" }, { value: "international", label: "국제기구", icon: "◎" }];

export default function ReportComposer() {
  const [query, setQuery] = useState(""); const [reportType, setReportType] = useState<ReportType>("one-page"); const [period, setPeriod] = useState<Period>("30d"); const [sources, setSources] = useState<Source[]>(["government", "research", "news"]);
  const [openaiKey, setOpenaiKey] = useState(""); const [geminiKey, setGeminiKey] = useState(""); const [keyStatus, setKeyStatus] = useState<"idle" | "saved" | "changed">("idle"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [apiResults, setApiResults] = useState<{ openai: ApiResult; gemini: ApiResult } | null>(null);
  const [selectedFile, setSelectedFile] = useState<File | null>(null); const [template, setTemplate] = useState<TemplateResult | null>(null); const [templateLoading, setTemplateLoading] = useState(false); const [templateError, setTemplateError] = useState("");

  useEffect(() => { const savedOpenai = sessionStorage.getItem(OPENAI_KEY) ?? ""; const savedGemini = sessionStorage.getItem(GEMINI_KEY) ?? ""; setOpenaiKey(savedOpenai); setGeminiKey(savedGemini); if (savedOpenai || savedGemini) setKeyStatus("saved"); }, []);
  const toggleSource = (source: Source) => setSources((current) => current.includes(source) ? current.filter((item) => item !== source) : [...current, source]);
  const onKeyChange = (setter: (value: string) => void, value: string) => { setter(value); setKeyStatus("changed"); setError(""); };
  const saveSession = () => { if (!openaiKey.trim() && !geminiKey.trim()) { setError("OpenAI 또는 Gemini API 키를 하나 이상 입력한 뒤 저장해 주세요."); setKeyStatus("idle"); return; } if (openaiKey.trim()) sessionStorage.setItem(OPENAI_KEY, openaiKey.trim()); else sessionStorage.removeItem(OPENAI_KEY); if (geminiKey.trim()) sessionStorage.setItem(GEMINI_KEY, geminiKey.trim()); else sessionStorage.removeItem(GEMINI_KEY); setKeyStatus("saved"); setError(""); };
  const clearSession = () => { sessionStorage.removeItem(OPENAI_KEY); sessionStorage.removeItem(GEMINI_KEY); setOpenaiKey(""); setGeminiKey(""); setKeyStatus("idle"); setError(""); };
  const resetInputAndResult = () => { setQuery(""); setReportType("one-page"); setPeriod("30d"); setSources(["government", "research", "news"]); setApiResults(null); setError(""); };
  const analyzeTemplate = async () => { if (!selectedFile) { setTemplateError("먼저 분석할 파일을 선택해 주세요."); return; } setTemplateLoading(true); setTemplateError(""); setTemplate(null); const form = new FormData(); form.append("file", selectedFile); try { const response = await fetch("/api/template", { method: "POST", body: form }); const result = await response.json() as TemplateResult & { ok: boolean }; if (!response.ok || !result.ok) throw new Error(result.error ?? "문서 분석에 실패했습니다."); setTemplate(result); } catch (requestError) { setTemplateError(requestError instanceof Error ? requestError.message : "문서 분석 중 오류가 발생했습니다."); } finally { setTemplateLoading(false); } };
  const generate = async () => { if (!openaiKey.trim() && !geminiKey.trim()) { setError("보고서 초안을 생성하려면 OpenAI 또는 Gemini API 키를 먼저 입력해 주세요."); return; } setLoading(true); setError(""); setApiResults(null); try { const response = await fetch("/api/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ openaiKey, geminiKey, query, reportType, period, sources, templateMarkdown: template?.markdown ?? "" }) }); const result = await response.json() as { openai: ApiResult; gemini: ApiResult }; if (!response.ok) throw new Error("검색 요청을 처리하지 못했습니다."); setApiResults(result); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "검색 요청 중 오류가 발생했습니다."); } finally { setLoading(false); } };

  return <div className="shell"><header className="topbar"><div className="topbar-inner"><div className="brand"><span className="brand-mark">I</span><span>IITP 이슈 대응센터</span></div><div className="top-actions"><span className="status-dot" /> 실시간 검색 <span>·</span> 초안 생성기</div></div></header><main className="main"><div className="hero"><div><p className="eyebrow">ISSUE RESPONSE & PERFORMANCE</p><h1>이슈 대응·성과 보고서<br />초안 생성기</h1><p>문서 양식의 구조를 분석해 실시간 검색 기반 보고서에 반영하세요.</p></div><div className="hero-note">v0.4 Template<br />kordoc</div></div><div className="workspace">
    <section className="card form-card"><div className="section-head"><h2 className="section-title">자료 입력 및 조건 설정</h2><span className="section-kicker">STEP 01 — 03</span></div><div className="key-panel"><div className="key-panel-head"><div><h3>API 키 설정</h3><p>현재 브라우저 탭에서만 사용됩니다.</p></div><span className={`key-status ${keyStatus}`}>{keyStatus === "saved" ? "● 세션 저장됨" : keyStatus === "changed" ? "● 저장 필요" : "○ 미저장"}</span></div><div className="key-grid"><div><label className="field-label" htmlFor="openai-key">OpenAI API 키</label><input id="openai-key" className="key-input" type="password" value={openaiKey} onChange={(event) => onKeyChange(setOpenaiKey, event.target.value)} placeholder="sk-..." autoComplete="off" /></div><div><label className="field-label" htmlFor="gemini-key">Gemini API 키</label><input id="gemini-key" className="key-input" type="password" value={geminiKey} onChange={(event) => onKeyChange(setGeminiKey, event.target.value)} placeholder="AIza..." autoComplete="off" /></div></div><p className="session-note">🔒 API 키는 sessionStorage에만 저장되며, 요청 본문으로만 전달됩니다.</p><div className="key-actions"><button className="secondary-button" type="button" onClick={saveSession}>세션 저장</button><button className="text-button" type="button" onClick={clearSession}>세션 비우기</button></div>{error && <p className="error-message" role="alert">⚠ {error}</p>}</div>
      <div className="template-panel"><div className="template-head"><div><h3>문서 양식 분석</h3><p>HWP·HWPX·DOCX·PDF·XLSX·XLS</p></div><span className="template-badge">kordoc</span></div><div className="template-upload"><input id="template-file" type="file" accept=".hwp,.hwpx,.docx,.pdf,.xlsx,.xls" onChange={(event) => { setSelectedFile(event.target.files?.[0] ?? null); setTemplate(null); setTemplateError(""); }} /><label htmlFor="template-file">{selectedFile ? selectedFile.name : "분석할 문서 양식 선택"}</label><button className="secondary-button" type="button" onClick={analyzeTemplate} disabled={templateLoading}>{templateLoading ? "분석 중…" : "양식 분석"}</button></div>{template && <p className="template-success" role="status">✓ {template.fileName} 분석 완료 · {template.fileType?.toUpperCase()} 구조를 보고서 프롬프트에 반영합니다.</p>}{template?.warnings?.length ? <p className="template-warning">참고: {template.warnings.map((warning) => warning.message).join(" · ")}</p> : null}{templateError && <p className="error-message" role="alert">⚠ {templateError}</p>}</div>
      <label className="field-label" htmlFor="query">키워드 또는 뉴스 기사 본문</label><textarea id="query" className="input-area" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={'예: 생성형 AI 관련 정부 정책 동향과 산업 영향\n\n뉴스 기사 본문을 붙여넣으면 핵심 이슈를 중심으로 정리합니다.'} /><p className="helper">분석된 양식이 있으면 제목·항목·문단 순서를 최대한 유지합니다.</p><div className="form-group"><span className="field-label">보고서 유형</span><div className="choice-row">{([["one-page", "보고용 1장 페이퍼"], ["status-response", "현황-문제점-대응방향"]] as [ReportType, string][]).map(([value, label]) => <div className="choice" key={value}><input id={value} type="radio" name="reportType" checked={reportType === value} onChange={() => setReportType(value)} /><label htmlFor={value}>{label}</label></div>)}</div></div><div className="form-group"><span className="field-label">검색 기간</span><div className="choice-row">{([["7d", "최근 7일"], ["30d", "최근 30일"], ["1y", "최근 1년"], ["all", "전체 기간"]] as [Period, string][]).map(([value, label]) => <div className="choice" key={value}><input id={`period-${value}`} type="radio" name="period" checked={period === value} onChange={() => setPeriod(value)} /><label htmlFor={value}>{label}</label></div>)}</div></div><div className="form-group"><span className="field-label">검색 소스 <span style={{ color: "#a0abba", fontWeight: 400 }}>· 복수 선택</span></span><div className="source-grid">{sourceOptions.map(({ value, label, icon }) => <div className="choice source-choice" key={value}><input id={`source-${value}`} type="checkbox" checked={sources.includes(value)} onChange={() => toggleSource(value)} /><label htmlFor={`source-${value}`}><span className="source-icon">{icon}</span>{label}</label></div>)}</div></div><button className="generate" type="button" onClick={generate} disabled={loading}>{loading ? "두 API에서 검색 중…" : "검색 및 양식 반영 초안 생성 →"}</button><button className="reset-button" type="button" onClick={resetInputAndResult}>입력·결과 리셋 <span>API 키 유지</span></button></section>
    <section className="card result-card"><div className="result-top"><h2>생성 결과</h2><span className="result-badge">LIVE SEARCH</span></div>{loading ? <div className="empty"><div><div className="empty-mark">◌</div><p>OpenAI Web Search와<br />Gemini Google Search를 호출하고 있습니다.</p></div></div> : apiResults ? <div className="api-results"><ApiResultCard name="OpenAI Web Search" result={apiResults.openai} /><ApiResultCard name="Gemini Google Search" result={apiResults.gemini} /></div> : <div className="empty"><div><div className="empty-mark">✦</div><p>왼쪽 조건을 설정하고<br /><strong>검색 및 초안 생성</strong>을 눌러주세요.</p></div></div>}</section></div></main></div>;
}

function ApiResultCard({ name, result }: { name: string; result: ApiResult }) { return <article className={`api-result ${result.ok ? "success" : "failure"}`}><div className="api-result-head"><h3>{name}</h3><span className={`api-state ${result.ok ? "success" : "failure"}`}>{result.ok ? "성공" : "실패"}</span></div>{result.ok ? <><div className="api-report"><p>{result.text}</p></div><div className="api-sources"><h4>참고 출처 ({result.sources.length})</h4>{result.sources.length ? <ol>{result.sources.map((source, index) => <li key={`${source.url}-${index}`}><a href={source.url} target="_blank" rel="noreferrer">[{index + 1}] {source.title}</a></li>)}</ol> : <p>추출된 URL 출처가 없습니다.</p>}</div></> : <p className="api-error">⚠ {result.error ?? "알 수 없는 API 오류"}</p>}</article>; }
